version: '3.8'

services:
    emails_php:
        container_name: emails_php
        build:
            context: ./php
        networks:
            - emails_network
        ports:
            - '9000:9000'
        volumes:
            - ../:/var/www/html

    emails_nginx:
        container_name: emails_nginx
        image: nginx:stable-alpine
        ports:
            - '8008:80'
        volumes:
            - ../:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - emails_php
        networks:
            - emails_network
            
    emails_rabbitmq:
        image: "rabbitmq:3.7-management"
        hostname: "rabbitmq"
        environment:
            RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
            RABBITMQ_DEFAULT_USER: "rabbitmq"
            RABBITMQ_DEFAULT_PASS: "rabbitmq"
            RABBITMQ_DEFAULT_VHOST: "/"
        ports:
            - "15671:15672"
            - "5671:5672"
        container_name: emails_rabbitmq
        networks:
            - emails_network        

networks:
    emails_network:
        external: true
        driver: bridge
